# Generated by Django 5.1.2 on 2024-10-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('idjogador', models.IntegerField(db_column='idJogador', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=25)),
                ('login', models.CharField(max_length=25)),
                ('senha', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'jogador',
                'managed': False,
            },
        ),
    ]
